### ISSUE TITLE
I think the DizzySasquatchsBeltstatcalculator.csproj file is missing

### ISSUE THREAD

**Issue by miaou56** [DizzySasquatch/DizzySasquatchsBeltstatcalculator#1]
I can't compile your app because it is missing the file I think the "DizzySasquatchsBeltstatcalculator.csproj" file is missing

**Comment by DizzySasquatch** [comment]
Sorry for that - I readded it
The project is from a time when I didnt't really had any idea how git worked and I guess I removed it for some reason
